version: '3.8'

services:
  tips-brasil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tips-brasil_app  # Atualizado para refletir o novo nome do projeto
    restart: always
    ports:
      - "3000:3000" # Expor a porta 3000
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/tips-brasil
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: tips-brasil_mongodb
    restart: always
    ports:
      - "27017:27017" # Expor a porta 27017 para acessar o MongoDB
    volumes:
      - mongo-data:/data/db # Volume para persistência de dados

volumes:
  mongo-data:
    driver: local
